[package]
name = "schedule-model"
description = "Data Transfer Objects"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
